# Narrow, single-purpose extractor for Win32 STRINGTABLE blocks inside a
# classic .rc resource script -- this is NOT a general .rc/.res compiler.
# It only understands lines shaped like:
#
#   SYMBOL   "quoted text"
#
# inside STRINGTABLE ... BEGIN ... END blocks, and resolves SYMBOL to a
# numeric ID via one or more "#define SYMBOL <number>" C/C++ headers.
# Everything else in the .rc file (icons, dialogs, version info, menus,
# bitmaps, ...) is ignored entirely.
#
# Required variable:
#   OUTPUT_CPP        - path to the generated .cpp file to write.
#
# Optional variables (RC_FILE and RESOURCE_HEADERS must both be set to
# extract real data; if either is unset/missing, an empty table is written
# so LoadStringA falls back to its placeholder behavior):
#   RC_FILE           - path to the .rc file containing STRINGTABLE blocks.
#   RC_ENCODING       - encoding of RC_FILE: "UTF-8" or "UTF-16LE" (default UTF-8).
#   RESOURCE_HEADERS  - list of headers with "#define SYMBOL <number>" lines
#                       resolving RC_FILE's STRINGTABLE symbols.

if(NOT DEFINED OUTPUT_CPP)
    message(FATAL_ERROR "ExtractStringTable.cmake: OUTPUT_CPP is required")
endif()

set(entries "")

if(DEFINED RC_FILE AND DEFINED RESOURCE_HEADERS)
    if(NOT EXISTS "${RC_FILE}")
        message(WARNING "ExtractStringTable.cmake: RC_FILE not found: ${RC_FILE} -- generating an empty string table")
    else()
        # Resolve symbol -> numeric id from all given resource headers.
        set(symbol_names "")
        set(symbol_values "")
        foreach(header IN LISTS RESOURCE_HEADERS)
            if(EXISTS "${header}")
                file(STRINGS "${header}" header_lines ENCODING UTF-8)
                foreach(hline IN LISTS header_lines)
                    if(hline MATCHES "^#define[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]+([0-9]+)[ \t]*$")
                        list(APPEND symbol_names "${CMAKE_MATCH_1}")
                        list(APPEND symbol_values "${CMAKE_MATCH_2}")
                    endif()
                endforeach()
            endif()
        endforeach()

        if(NOT RC_ENCODING)
            set(RC_ENCODING "UTF-8")
        endif()
        file(STRINGS "${RC_FILE}" rc_lines ENCODING ${RC_ENCODING})

        set(in_table FALSE)
        foreach(rline IN LISTS rc_lines)
            string(REGEX REPLACE "\t" " " normalized "${rline}")
            string(STRIP "${normalized}" trimmed)

            if(NOT in_table)
                if(trimmed STREQUAL "STRINGTABLE" OR trimmed MATCHES "^STRINGTABLE[ ]")
                    set(in_table TRUE)
                endif()
                continue()
            endif()

            if(trimmed STREQUAL "BEGIN")
                continue()
            endif()
            if(trimmed STREQUAL "END")
                set(in_table FALSE)
                continue()
            endif()

            if(trimmed MATCHES "^([A-Za-z_][A-Za-z0-9_]*) +\"(.*)\"$")
                set(sym "${CMAKE_MATCH_1}")
                set(text "${CMAKE_MATCH_2}")
                list(FIND symbol_names "${sym}" sym_idx)
                if(sym_idx GREATER -1)
                    list(GET symbol_values ${sym_idx} numeric_id)
                    # Escape a literal double-quote; leave existing C-style
                    # escapes (e.g. "\n") untouched so they keep their
                    # meaning in the generated C++ string literal.
                    string(REPLACE "\"" "\\\"" text_escaped "${text}")
                    list(APPEND entries "    {${numeric_id}u, \"${text_escaped}\"},")
                endif()
            endif()
        endforeach()
    endif()
endif()

list(LENGTH entries entry_count)

set(content "// Auto-generated by cmake/ExtractStringTable.cmake. Do not edit by hand.\n")
string(APPEND content "// Extracted from: ${RC_FILE}\n")
string(APPEND content "#include \"internal/FreeApiGeneratedStrings.hpp\"\n\n")
string(APPEND content "namespace FreeApi::Internal {\n\n")
string(APPEND content "const GeneratedStringEntry g_generatedStringTable[] = {\n")
foreach(entry IN LISTS entries)
    string(APPEND content "${entry}\n")
endforeach()
if(entry_count EQUAL 0)
    string(APPEND content "    {0u, nullptr},\n")
endif()
string(APPEND content "};\n\n")
string(APPEND content "const std::size_t g_generatedStringTableCount = ${entry_count};\n\n")
string(APPEND content "} // namespace FreeApi::Internal\n")

file(WRITE "${OUTPUT_CPP}" "${content}")

message(STATUS "ExtractStringTable.cmake: wrote ${entry_count} string(s) to ${OUTPUT_CPP}")
